export const site = {
  name: "Rachat Bijoux Nice",
  brandName: "Rachat Bijoux Nice",
  legalName: "Rachat Bijoux Nice — Maison Obagem",
  domain: "rachat-bijoux-nice.site",
  url: "https://rachat-bijoux-nice.site",
  city: "Nice",
  citySlug: "nice",
  postalCode: "06000",
  department: "Alpes-Maritimes",
  region: "Provence-Alpes-Côte d'Azur",
  regionContext: "Nice (06000 / 06100 / 06200 / 06300) — Promenade des Anglais, Carré d'Or, Place Masséna, Mont Boron, Cap de Nice, Cimiez, Vieux-Nice, Port Lympia, Saint-Jean-Cap-Ferrat, Villefranche-sur-Mer, Beaulieu-sur-Mer, Monaco, Antibes et Cannes",
  tagline: "Cabinet Gemmologique & Rachat de Haute Joaillerie à Nice (Carré d'Or & Promenade)",
  description: "Rachat Bijoux Nice : expertise gemmologique indépendante et rachat immédiat de diamants certifiés (GIA, HRD, IGI) selon le cours officiel Rapaport, haute joaillerie signée (Cartier, Van Cleef & Arpels, Bulgari, Boucheron, Chaumet), or 18k et montres de prestige (Rolex, Patek Philippe, Audemars Piguet). Salons privés au Carré d'Or / Place Masséna et expertises confidentielles à domicile à Nice, Mont Boron, Cap d'Ail, Saint-Jean-Cap-Ferrat, Monaco et sur toute la Côte d'Azur. Paiement sécurisé par virement bancaire immédiat.",
  port: 3850,

  phone: "+33 1 48 87 81 44",
  phoneDisplay: "01 48 87 81 44",
  phoneIntl: "+33148878144",
  whatsappPhone: "+33148878144",
  email: "contact@rachat-bijoux-nice.site",
  whatsappUrl: "https://wa.me/33148872337",

  address: {
    street: "2 Avenue de Verdun",
    postalCode: "06000",
    city: "Nice",
    region: "Provence-Alpes-Côte d'Azur",
    country: "FR",
    geo: { lat: 43.6961, lng: 7.2685 },
  },

  openingHours: [
    { day: "Lundi - Vendredi", hours: "09:30 - 18:30" },
    { day: "Samedi", hours: "10:00 - 17:30 (sur rendez-vous)" },
    { day: "Dimanche", hours: "Fermé" },
  ],

  stats: [
    { value: "40+", label: "Années d'Expertise" },
    { value: "100%", label: "Virement Immédiat" },
    { value: "GIA / HRD", label: "Gemmologues Diplômés" },
    { value: "Rapaport", label: "Cours Officiel Diamants" },
  ],

  areasServed: [
    "Nice",
    "Promenade des Anglais",
    "Carré d'Or",
    "Place Masséna",
    "Avenue de Verdun",
    "Rue Paradis",
    "Mont Boron",
    "Cap de Nice",
    "Cimiez",
    "Vieux-Nice",
    "Port Lympia",
    "Saint-Jean-Cap-Ferrat",
    "Villefranche-sur-Mer",
    "Beaulieu-sur-Mer",
    "Èze",
    "Monaco",
    "Cap d'Ail",
    "Antibes",
    "Cap d'Antibes",
    "Cannes",
    "Côte d'Azur",
  ],
};
